name: example
description: Example app of yalo package
version: 1.0.0

environment:
  sdk: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  pedantic: ^1.9.0
  yalo:
    path: ../
  yalo_locale:
    path: ./.yalo_locale
  yalo_assets:
    path: ./.yalo_assets

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/