name: yalo
description: Yalo (Yaml localizations) - is a package, which give you a simplest way to get localizations from yaml files
version: 1.0.1
homepage: https://github.com/alphamikle/yalo

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  dart_style: ^1.3.6
  yaml: ^2.2.1
  path: ^1.7.0
  analyzer: ^0.39.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: